sudo: required
services: 
  - docker

before_install: 
  - docker build -t thetkpark/udemy-docker-react -f Dockerfile.dev .

script: 
  - docker run thetkpark/udemy-docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-458140489083"
  bucket_path: "udemy-docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

  


  

